import { PlannerState } from '../types/planner';

export const INITIAL_PLANNER_DATA: PlannerState = {
  companyName: 'Gestão PR Negócios',
  responsibleName: 'Paulo Ricardo',
  planningPeriod: '2026 - Estratégico Anual',
  targetAnnualRevenue: 1200000,
  targetMonthlyRevenue: 100000,
  currentActualRevenue: 78500,
  averageTicket: 5000,
  leadToOpportunityRate: 30, // 30%
  opportunityToProposalRate: 50, // 50%
  proposalToSaleRate: 35, // 35%
  channels: [
    {
      id: 'c1',
      name: 'Indicações & Networking (B2B)',
      percentage: 40,
      targetRevenue: 40000,
      actualRevenue: 34000,
      leadsTarget: 25,
      leadsActual: 22,
      conversionRate: 45,
    },
    {
      id: 'c2',
      name: 'Inbound Marketing & Tráfego Pago',
      percentage: 30,
      targetRevenue: 30000,
      actualRevenue: 22500,
      leadsTarget: 120,
      leadsActual: 105,
      conversionRate: 15,
    },
    {
      id: 'c3',
      name: 'Outbound Comercial & Prospecção Ativa',
      percentage: 20,
      targetRevenue: 20000,
      actualRevenue: 15000,
      leadsTarget: 80,
      leadsActual: 65,
      conversionRate: 20,
    },
    {
      id: 'c4',
      name: 'Base de Clientes (Upsell / Cross-sell)',
      percentage: 10,
      targetRevenue: 10000,
      actualRevenue: 7000,
      leadsTarget: 15,
      leadsActual: 12,
      conversionRate: 60,
    },
  ],
  team: [
    {
      id: 'rep1',
      name: 'Paulo Ricardo',
      role: 'Head Comercial / Executivo',
      targetRevenue: 60000,
      actualRevenue: 48500,
      commissionRate: 5,
      dealsClosed: 9,
    },
    {
      id: 'rep2',
      name: 'Consultor de Vendas 01',
      role: 'Closer B2B',
      targetRevenue: 25000,
      actualRevenue: 18000,
      commissionRate: 4,
      dealsClosed: 4,
    },
    {
      id: 'rep3',
      name: 'Consultor de Vendas 02',
      role: 'SDR / Inside Sales',
      targetRevenue: 15000,
      actualRevenue: 12000,
      commissionRate: 3.5,
      dealsClosed: 3,
    },
  ],
  monthlyMilestones: [
    { month: 'Jan', target: 80000, actual: 82000, status: 'completed' },
    { month: 'Fev', target: 85000, actual: 87500, status: 'completed' },
    { month: 'Mar', target: 90000, actual: 91000, status: 'completed' },
    { month: 'Abr', target: 95000, actual: 93500, status: 'completed' },
    { month: 'Mai', target: 100000, actual: 98000, status: 'completed' },
    { month: 'Jun', target: 100000, actual: 105000, status: 'completed' },
    { month: 'Jul', target: 105000, actual: 102000, status: 'completed' },
    { month: 'Ago', target: 110000, actual: 112500, status: 'completed' },
    { month: 'Set', target: 100000, actual: 78500, status: 'pending' },
    { month: 'Out', target: 115000, actual: 0, status: 'pending' },
    { month: 'Nov', target: 120000, actual: 0, status: 'pending' },
    { month: 'Dez', target: 130000, actual: 0, status: 'pending' },
  ],
  notes: 'Foco do trimestre: aumentar taxa de qualificação no primeiro contato e acelerar propostas B2B com ticket acima de R$ 5.000.',
};
